export const data=[
    {
        id: 1,
        image: "../Image/House1.jpg",
        name: "Red Carpet Real Estate",
        location: "210 Zirak Road, Canada",
        address:'Canada',
        category: "For Rent",
        price: "3700",
        type: "House",
      },
      {
        id: 2,
        image: "../Image/House2.jpg",
        name: "Fairmount Properties",
        location: "5698 Zirak Road, NewYork",
        address:'New York',
        category: "For Sale",
        price: "9750",
        type: "House",
      },
      {
        id: 3,
        image: "../Image/House3.jpg",
        name: "The Real Estate Corner",
        location: "5624 Mooker Market, USA",
        address:'New York',
        category: "For Rent",
        price: "5860",
        type: "House",
      },
      {
        id: 4,
        image: "../Image/House4.jpg",
        name: "Herringbone Realty",
        location: "5621 Liverpool, London",
        address:'New York',
        category: "For Sale",
        price: "7540",
        type: "House",
      },
      {
        id: 5,
        image: "../Image/House5.jpg",
        name: "Brick Lane Realty",
        location: "210 Montreal Road, Canada",
        address:'Canada',
        category: "For Rent",
        price: "4850",
        type: "House",
      },
      {
        id: 6,
        image: "../Image/House6.jpg",
        name: "Banyon Tree Realty",
        location: "210 Zirak Road, Canada",
        address:'Canada',
        category: "For Sale",
        price: "2742",
        type: "House",
      },
      {
        id: 7,
        image: "../Image/House7.jpg",
        name: "Red Carpet Real Estate",
        location: "210 Zirak Road, Canada",
        address:'Canada',
        category: "For Rent",
        price: "3700",
        type: "House",
      },
      {
        id: 8,
        image: "../Image/House8.jpg",
        name: "Fairmount Properties",
        location: "5698 Zirak Road, NewYork",
        address:'New York',
        category: "For Sale",
        price: "9750",
        type: "House",
      },
      {
        id: 9,
        image: "../Image/House9.jpg",
        name: "The Real Estate Corner",
        location: "5624 Mooker Market, USA",
        address:'New York',
        category: "For Rent",
        price: "5860",
        type: "House",
      },
      {
        id: 10,
        image: "../Image/House10.jpg",
        name: "Herringbone Realty",
        location: "5621 Liverpool, London",
        address:'New York',
        category: "For Sale",
        price: "7540",
        type: "House",
      },
      {
        id: 11,
        image: "../Image/Flat1.jpg",
        name: "Red Carpet Real Estate",
        location: "210 Zirak Road, Canada",
        address:'Canada',
        category: "For Rent",
        price: "3700",
        type: "Flat",
      },
      {
        id: 12,
        image: "../Image/Flat2.jpg",
        name: "Fairmount Properties",
        location: "5698 Zirak Road, NewYork",
        address:'New York',
        category: "For Sale",
        price: "9750",
        type: "Flat",
      },
      {
        id: 13,
        image: "../Image/Flat3.jpg",
        name: "The Real Estate Corner",
        location: "5624 Mooker Market, USA",
        address:'New York',
        category: "For Rent",
        price: "5860",
        type: "Flat",
      },
      {
        id: 14,
        image: "../Image/Flat4.jpg",
        name: "Herringbone Realty",
        location: "5621 Liverpool, London",
        address:'New York',
        category: "For Sale",
        price: "7540",
        type: "Flat",
      },
      {
        id: 15,
        image: "../Image/Flat5.jpg",
        name: "Brick Lane Realty",
        location: "210 Montreal Road, Canada",
        address:'Canada',
        category: "For Rent",
        price: "4850",
        type: "Flat",
      },
      {
        id: 16,
        image: "../Image/Flat6.jpg",
        name: "Banyon Tree Realty",
        location: "210 Zirak Road, Canada",
        address:'Canada',
        category: "For Sale",
        price: "2742",
        type: "Flat",
      },
      {
        id: 17,
        image: "../Image/Flat7.jpg",
        name: "Red Carpet Real Estate",
        location: "210 Zirak Road, Canada",
        address:'Canada',
        category: "For Rent",
        price: "3700",
        type: "Flat",
      },
      {
        id: 18,
        image: "../Image/Flat8.png",
        name: "Fairmount Properties",
        location: "5698 Zirak Road, NewYork",
        address:'New York',
        category: "For Sale",
        price: "9750",
        type: "Flat",
      },
      {
        id: 19,
        image: "../Image/Flat9.jpg",
        name: "The Real Estate Corner",
        location: "5624 Mooker Market, USA",
        address:'New York',
        category: "For Rent",
        price: "5860",
        type: "Flat",
      },
      {
        id: 20,
        image: "../Image/Flat10.jpg",
        name: "Herringbone Realty",
        location: "5621 Liverpool, London",
        address:'New York',
        category: "For Sale",
        price: "7540",
        type: "Flat",
      },
]